# index -> (unit, loadout, confident)
# confident=True means vision-matched against a PDF page I've already reviewed
# this session. confident=False means a best-effort guess from weapon/pose
# silhouette against the roster's loadout vocabulary -- NOT verified, revisit
# once more of the book is reviewed. See PROGRESS notes.
IDENTIFICATIONS = {
    1: ("Company Leader", "Master Drum Pistol", True),
    2: ("Company Leader", "Master Rifle", True),
    3: ("Storm Leader", "Master Heavy Rifle", False),
    4: ("Storm Leader", "Master Sniper Rifle", False),
    5: ("Combat Bikers", "Default", True),
    6: ("Combat Bikers", "Hunting Lance", True),
    7: ("Company Leader", "Forward Observer", False),
    8: ("Company Leader", "Drill Sergeant", False),
    9: ("Company Leader", "Commander", False),
    10: ("Infantry Squad", "Field Radio", False),
    11: ("Company Leader", "Munitioner", False),
    12: ("Company Leader", "Psy-Hacker", False),
    13: ("Company Leader", "Sniper Leader", True),
    14: ("Infantry Squad", "Drum Rifle", False),
    15: ("Infantry Squad", "Fusion Rifle", False),
    16: ("Infantry Squad", "Plasma Rifle", False),
    17: ("Infantry Squad", "Grenade Launcher", False),
    18: ("Infantry Squad", "Sniper Rifle", False),
    19: ("Infantry Squad", "Laser Rifle", False),
    20: ("Infantry Squad", "Drum Pistol", False),
    21: ("Infantry Squad", "Fusion Rifle", False),
    22: ("Infantry Squad", "Plasma Pistol", False),
    23: ("Infantry Squad", "Field Radio", True),
    24: ("Infantry Squad", "Flamer", True),
    25: ("Infantry Squad", "Company Standard", True),
    26: ("Recruits", "Default", True),
    27: ("GRUNT Robots", "Default", True),
    28: ("Weapon Teams", "Default", False),
    29: ("Weapon Teams", "Missile Launcher", False),
    30: ("Weapon Teams", "Heavy Machinegun", False),
    31: ("Weapon Teams", "Laser Cannon", False),
    32: ("Weapon Teams", "HE Autocannon", False),
    33: ("Veterans", "Drum Rifle", False),
    34: ("Veterans", "Fusion Rifle", False),
    35: ("Veterans", "Plasma Rifle", False),
    36: ("Veterans", "Shotgun", False),
    37: ("Veterans", "Sniper Rifle", False),
    38: ("Veterans", "Grenade Launcher", False),
    39: ("Veterans", "Flamer", False),
    40: ("Veterans", "Field Radio", False),
    41: ("Veterans", "Company Standard", True),
    42: ("Veterans", "Medical Training", False),
    43: ("Veterans", "Demo Charge", False),
    44: ("Veterans", "Sgt. Hand Weapon", False),
    45: ("Storm Leader", "Master Drum Pistol", False),
    46: ("Storm Leader", "Master Plasma Pistol", False),
    47: ("Storm Leader", "Commander", False),
    48: ("Storm Leader", "Drill Sergeant", False),
    49: ("Storm Leader", "Forward Observer", False),
    50: ("Storm Leader", "General", False),
    51: ("Storm Leader", "Munitioner", False),
    52: ("Storm Leader", "Psy-Hacker", False),
    53: ("Storm Leader", "Wolf-Dog Companion", False),
    54: ("Storm Leader", "Default", False),
    55: ("Storm Leader", "Orbital Drop", False),
    56: ("Storm Leader", "Energy Sword", False),
    57: ("Sappers", "Default", False),
    58: ("Sappers", "Drum Rifle", False),
    59: ("Sappers", "Fusion Rifle", False),
    60: ("Sappers", "Rapid Laser Rifle", False),
    61: ("Sappers", "Rapid Plasma Rifle", False),
    62: ("Sappers", "Flamer", False),
    63: ("Snipers", "Default", True),
    64: ("Combat Bikers", "Laser Rifle", False),
    65: ("Combat Bikers", "Grenade Launcher", False),
    66: ("OGRE Robots", "Bash", False),
    67: ("OGRE Robots", "Shock Baton", False),
    68: ("OGRE Robots", "Combat Axe", False),
    69: ("OGRE Robots", "Light Grenade Launcher", False),
}
